/**
 * This code was generated by Builder.io.
 */
import { Component } from "@angular/core";

@Component({
  selector: "app-my-component",
  template: `
    <div
      class="overflow-hidden bg-zinc-100 rounded-[30px] shadow-[0px_4px_4px_rgba(0,0,0,0.25)]"
    >
      <div class="flex gap-5 max-md:flex-col">
        <aside class="flex flex-col w-[24%] max-md:ml-0 max-md:w-full">
          <nav
            class="flex flex-col pb-14 mx-auto w-full bg-blue-500 rounded-none"
          >
            <header
              class="flex gap-4 items-start px-14 py-14 text-white bg-blue-600 max-md:px-5"
            >
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/da9cf981840c2ef27049dea47632c0636a991fa54334d76c0cc57ea8e64ebcf4?placeholderIfAbsent=true&apiKey=acd33750e364423796cf9d346ab258d6"
                alt=""
                class="object-contain shrink-0 w-14 rounded-full aspect-square"
              />
              <div class="flex flex-col mt-1.5">
                <h2 class="self-start text-base font-medium">Lorem</h2>
                <p class="text-xs">Lorem ipsum dolor sit amet</p>
              </div>
            </header>
            <ul
              class="flex flex-col items-start px-10 mt-5 w-full text-base font-medium text-white max-md:px-5"
            >
              <li class="flex gap-4 justify-center items-center mt-7">
                <img
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/67b04b071727a47230bfff36dbbe95acab5aad53adc7c23e1261cf1f2be55d65?placeholderIfAbsent=true&apiKey=acd33750e364423796cf9d346ab258d6"
                  alt=""
                  class="object-contain shrink-0 self-stretch my-auto w-5 aspect-square"
                />
                <span class="self-stretch my-auto">Lorem ipsum dolor</span>
              </li>
              <li
                class="flex gap-4 justify-center items-center w-full bg-indigo-900 py-5 pr-7 pl-12 mt-7 max-md:px-5"
              >
                <img
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/a0069dd019c4bd3291a86f0d05297f50b555786cdbf785456d34b3b106379b83?placeholderIfAbsent=true&apiKey=acd33750e364423796cf9d346ab258d6"
                  alt=""
                  class="object-contain shrink-0 self-stretch my-auto w-5 aspect-square"
                />
                <span class="self-stretch my-auto">Lorem ipsum dolor</span>
                <div
                  class="flex gap-1.5 items-start self-stretch my-auto ml-auto"
                >
                  <img
                    loading="lazy"
                    src="https://cdn.builder.io/api/v1/image/assets/TEMP/394aa8269fccc60312da89fa4471d6a2b56069028d1489c1aa4dada037eff9ad?placeholderIfAbsent=true&apiKey=acd33750e364423796cf9d346ab258d6"
                    alt=""
                    class="object-contain shrink-0 w-6 aspect-square"
                  />
                  <img
                    loading="lazy"
                    src="https://cdn.builder.io/api/v1/image/assets/TEMP/423d25ac270bd8759431558dc15208d642ae9dc6a130f9e712cf1044566267b0?placeholderIfAbsent=true&apiKey=acd33750e364423796cf9d346ab258d6"
                    alt=""
                    class="object-contain shrink-0 w-6 aspect-square"
                  />
                </div>
              </li>
              <li class="flex gap-4 items-start mt-5">
                <img
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/f57b8160d6e73c62fedef0f9386ed82de847f8363458a7878b60d6bfb92be4c0?placeholderIfAbsent=true&apiKey=acd33750e364423796cf9d346ab258d6"
                  alt=""
                  class="object-contain shrink-0 w-5 aspect-square"
                />
                <span>Lorem ipsum dolor sit</span>
              </li>
              <li class="flex gap-4 justify-center items-center mt-7">
                <img
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/67b04b071727a47230bfff36dbbe95acab5aad53adc7c23e1261cf1f2be55d65?placeholderIfAbsent=true&apiKey=acd33750e364423796cf9d346ab258d6"
                  alt=""
                  class="object-contain shrink-0 self-stretch my-auto w-5 aspect-square"
                />
                <span class="self-stretch my-auto">Lorem ipsum dolor</span>
              </li>
              <li class="flex gap-4 justify-center items-center mt-7">
                <img
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/67b04b071727a47230bfff36dbbe95acab5aad53adc7c23e1261cf1f2be55d65?placeholderIfAbsent=true&apiKey=acd33750e364423796cf9d346ab258d6"
                  alt=""
                  class="object-contain shrink-0 self-stretch my-auto w-5 aspect-square"
                />
                <span class="self-stretch my-auto">Lorem ipsum dolor sit</span>
              </li>
              <li
                class="flex gap-3.5 justify-center items-center mt-24 max-md:mt-10"
              >
                <img
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/8ed13dd3ab372349efe7aab334ec85e071cd70726fac53f85b914c4557429d23?placeholderIfAbsent=true&apiKey=acd33750e364423796cf9d346ab258d6"
                  alt=""
                  class="object-contain shrink-0 self-stretch my-auto w-6 aspect-square"
                />
                <span class="self-stretch my-auto">Guias e FAQ</span>
              </li>
            </ul>
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/baf54116bb117876c0157f0306c3db6ea1f0937f07c3673823ff0cbcbe39ee07?placeholderIfAbsent=true&apiKey=acd33750e364423796cf9d346ab258d6"
              alt=""
              class="object-contain mt-5 w-full aspect-[333.33]"
            />
            <button
              class="flex gap-3.5 justify-center items-center self-start mt-5 ml-10 text-base font-medium text-white whitespace-nowrap max-md:ml-2.5"
            >
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/5b4f1b68409eb8b4a10d8bfc4e766d9d63e3b16201a7e9061661c3c11819b284?placeholderIfAbsent=true&apiKey=acd33750e364423796cf9d346ab258d6"
                alt=""
                class="object-contain shrink-0 self-stretch my-auto w-6 aspect-square"
              />
              <span class="self-stretch my-auto">Upgrade</span>
            </button>
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/baf54116bb117876c0157f0306c3db6ea1f0937f07c3673823ff0cbcbe39ee07?placeholderIfAbsent=true&apiKey=acd33750e364423796cf9d346ab258d6"
              alt=""
              class="object-contain mt-5 w-full aspect-[333.33]"
            />
            <button
              class="flex gap-3 justify-center items-center self-start mt-5 ml-10 text-base font-medium text-white whitespace-nowrap max-md:ml-2.5"
            >
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/fecf15855c305b85e14c91509660ac42d12f7ee302761b4ce82ad81ca216bd6b?placeholderIfAbsent=true&apiKey=acd33750e364423796cf9d346ab258d6"
                alt=""
                class="object-contain shrink-0 self-stretch my-auto w-6 aspect-square"
              />
              <span class="self-stretch my-auto">Configurações</span>
            </button>
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/baf54116bb117876c0157f0306c3db6ea1f0937f07c3673823ff0cbcbe39ee07?placeholderIfAbsent=true&apiKey=acd33750e364423796cf9d346ab258d6"
              alt=""
              class="object-contain mt-5 w-full aspect-[333.33]"
            />
            <div
              class="flex flex-col items-start pr-16 pl-6 mt-5 w-full text-base font-medium text-white max-md:px-5"
            >
              <button
                class="flex gap-4 justify-center items-center ml-4 whitespace-nowrap max-md:ml-2.5"
              >
                <img
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/b109ac07fa3519e9716b1af4e062edd4bf90aded6da95bf4117d36166f9e1a11?placeholderIfAbsent=true&apiKey=acd33750e364423796cf9d346ab258d6"
                  alt=""
                  class="object-contain shrink-0 self-stretch my-auto w-6 aspect-square"
                />
                <span class="self-stretch my-auto">Sair</span>
              </button>
              <button
                class="flex gap-4 justify-center items-center px-16 py-4 mt-11 bg-cyan-500 rounded-xl max-md:px-5 max-md:mt-10"
              >
                <img
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/22987788893ddc2fe23be6763e2217952d9faf1711a0900c7eac2819b3dd2abd?placeholderIfAbsent=true&apiKey=acd33750e364423796cf9d346ab258d6"
                  alt=""
                  class="object-contain shrink-0 self-stretch my-auto w-6 aspect-square"
                />
                <span class="self-stretch my-auto">Novo Chat</span>
              </button>
              <div
                class="flex gap-2 items-center self-center mt-5 max-w-full w-[164px]"
              >
                <img
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/b7f469a1f38f7c10854db4546246c6519d6502aa289c608426c9b68ff5464ea9?placeholderIfAbsent=true&apiKey=acd33750e364423796cf9d346ab258d6"
                  alt="AI assistant avatar"
                  class="object-contain shrink-0 self-stretch my-auto aspect-square rounded-[300px] w-[58px]"
                />
                <span class="self-stretch my-auto">Ai assistente</span>
              </div>
            </div>
          </nav>
        </aside>
        <main class="flex flex-col ml-5 w-[76%] max-md:ml-0 max-md:w-full">
          <section
            class="flex flex-col items-center mt-96 w-full font-medium max-md:mt-10 max-md:max-w-full"
          >
            <article
              class="flex flex-wrap gap-5 items-center p-5 text-base rounded-xl bg-neutral-800 text-neutral-300 max-md:max-w-full"
            >
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/32d6730ed6882bdb99700efcfbe366ea7f4f2342009e1205f3b7a2e55add9f5d?placeholderIfAbsent=true&apiKey=acd33750e364423796cf9d346ab258d6"
                alt="User avatar"
                class="object-contain shrink-0 self-stretch my-auto rounded-full aspect-square w-[70px]"
              />
              <p class="self-stretch my-auto w-[566px] max-md:max-w-full">
                Lorem ipsum dolor sit amet consectetur. Aenean feugiat hac
                maecenas eleifend quisque fringilla mattis lacus tempor.
                Ultrices.
              </p>
            </article>
            <article
              class="flex flex-wrap gap-8 items-start py-5 pr-2.5 pl-8 mt-12 max-w-full text-base border-l-2 bg-neutral-800 border-slate-500 shadow-[0px_4px_8px_rgba(185,185,185,0.3)] text-neutral-300 w-[694px] max-md:pl-5 max-md:mt-10"
            >
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/d50038c83e44738d3853fb86e0ad96e53e4477d046cd4ca3459686a2f35209e8?placeholderIfAbsent=true&apiKey=acd33750e364423796cf9d346ab258d6"
                alt="AI assistant avatar"
                class="object-contain shrink-0 aspect-square rounded-[300px] w-[70px]"
              />
              <p class="grow shrink w-[540px] max-md:max-w-full">
                Lorem ipsum dolor sit amet consectetur. Augue justo vulputate
                posuere dignissim. Ac luctus ridiculus natoque ullamcorper. Duis
                elit.
              </p>
            </article>
            <div
              class="flex flex-col justify-center items-center self-stretch px-20 py-14 mt-32 bg-white bg-opacity-10 max-md:px-5 max-md:mt-10 max-md:max-w-full"
            >
              <div class="flex flex-col ml-5 max-w-full w-[729px]">
                <div
                  class="flex flex-wrap gap-10 w-full text-sm max-md:max-w-full"
                >
                  <div class="flex flex-auto gap-6 max-md:max-w-full">
                    <button
                      class="flex gap-2 justify-center items-center px-4 py-2.5 text-red-600 rounded-md bg-red-600 bg-opacity-20"
                    >
                      <img
                        loading="lazy"
                        src="https://cdn.builder.io/api/v1/image/assets/TEMP/048edb00b107d8bcc26684850e567b5cb7c1a8e9153e17cccea8c7ad776413be?placeholderIfAbsent=true&apiKey=acd33750e364423796cf9d346ab258d6"
                        alt=""
                        class="object-contain shrink-0 self-stretch my-auto w-4 aspect-[0.89]"
                      />
                      <span class="self-stretch my-auto"
                        >Delete last generation</span
                      >
                    </button>
                    <button
                      class="flex gap-2.5 justify-center items-center px-4 py-2.5 text-green-500 rounded-md bg-green-500 bg-opacity-20"
                    >
                      <img
                        loading="lazy"
                        src="https://cdn.builder.io/api/v1/image/assets/TEMP/d7d26ea5cfae32d73934375f33a6d4e4d76e339a6bec712338577fed405757da?placeholderIfAbsent=true&apiKey=acd33750e364423796cf9d346ab258d6"
                        alt=""
                        class="object-contain shrink-0 self-stretch my-auto aspect-[0.83] w-[15px]"
                      />
                      <span class="self-stretch my-auto"
                        >Regenerate Generation</span
                      >
                    </button>
                  </div>
                  <div
                    class="flex gap-2.5 justify-center items-center my-auto text-stone-900"
                  >
                    <div
                      class="flex gap-2.5 justify-center items-center self-stretch my-auto"
                    >
                      <img
                        loading="lazy"
                        src="https://cdn.builder.io/api/v1/image/assets/TEMP/82aad2f169dba35f5d89487810c79898e53d21bd4638ecb3cdfc700ed09902f8?placeholderIfAbsent=true&apiKey=acd33750e364423796cf9d346ab258d6"
                        alt=""
                        class="object-contain shrink-0 self-stretch my-auto aspect-square w-[18px]"
                      />
                      <span class="self-stretch my-auto"
                        >Palavras Usadas: 12000</span
                      >
                    </div>
                  </div>
                </div>
                <form
                  class="flex gap-10 items-start px-8 py-4 mt-8 max-w-full text-base rounded-xl border border-solid border-slate-600 border-opacity-30 text-slate-600 text-opacity-50 w-[694px] max-md:px-5"
                >
                  <label
                    for="translateInput"
                    class="flex gap-2.5 min-w-[240px] w-[307px]"
                  >
                    <img
                      loading="lazy"
                      src="https://cdn.builder.io/api/v1/image/assets/TEMP/9d09044d11b6eb6389cb739ff244a0ae43aa137945b81857b82b3d21198ffff8?placeholderIfAbsent=true&apiKey=acd33750e364423796cf9d346ab258d6"
                      alt=""
                      class="object-contain shrink-0 w-6 aspect-square"
                    />
                    <span class="flex-auto w-[268px]"
                      >Traduza qualquer sinal para texto</span
                    >
                  </label>
                  <input
                    type="text"
                    id="translateInput"
                    class="sr-only"
                    aria-label="Traduza qualquer sinal para texto"
                  />
                </form>
                <button
                  class="z-10 self-end -mt-14 mr-9 w-14 h-14 bg-blue-600 rounded-none max-md:mr-2.5"
                >
                  <img
                    loading="lazy"
                    src="https://cdn.builder.io/api/v1/image/assets/TEMP/6ad180e1-833c-422d-8ec8-685c0afa9553?placeholderIfAbsent=true&apiKey=acd33750e364423796cf9d346ab258d6"
                    alt="Send"
                    class="object-contain w-full h-full"
                  />
                </button>
              </div>
            </div>
          </section>
        </main>
      </div>
    </div>
  `,
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
})
export class MyComponentComponent {}
